#!/usr/bin/env -S deno run --allow-all
// ${SHAWL_NAME} script: ${SHAWL_BASENAME}
// Generated by: shawl init

/**
 * Example function that can be called with druid mode
 */
export function ${SHAWL_BASENAME}(...args: string[]) {
    console.log("Hello from Deno!");
    console.log("Args:", args);
    
    // Access environment variables
    console.log("SHAWL_PATH:", Deno.env.get("SHAWL_PATH"));
}

// Run directly if executed as main module
if (import.meta.main) {
    ${SHAWL_BASENAME}(...Deno.args);
}
