// ${SHAWL_NAME} script: ${SHAWL_BASENAME}
// Generated by: shawl init

public class ${SHAWL_BASENAME} {
    /**
     * Example method that can be called with druid mode
     */
    public static void ${SHAWL_BASENAME}(String[] args) {
        System.out.println("Hello from Java!");
        System.out.println("Args: " + String.join(", ", args));
        
        // Access environment variables
        System.out.println("SHAWL_PATH: " + System.getenv("SHAWL_PATH"));
    }
    
    /**
     * Main entry point for exec mode
     */
    public static void main(String[] args) {
        if (args.length > 0 && args[0].equals("${SHAWL_BASENAME}")) {
            // Druid mode - call specific method
            String[] methodArgs = new String[args.length - 1];
            System.arraycopy(args, 1, methodArgs, 0, args.length - 1);
            ${SHAWL_BASENAME}(methodArgs);
        } else {
            // Direct execution
            ${SHAWL_BASENAME}(args);
        }
    }
}
