name = "java"

[default]
executable = "/bin/bash"
args = ["-c", "javac ${SHAWL_FILEPATH} && java -cp $(dirname ${SHAWL_FILEPATH}) ${SHAWL_BASENAME}"]
envs = {}

[druid]
executable = "/bin/bash"
args = ["-c", "javac ${SHAWL_FILEPATH} && java -cp $(dirname ${SHAWL_FILEPATH}) ${SHAWL_BASENAME} ${SHAWL_FUNCTION} \"$@\"", "--"]
envs = {}

[exec]
executable = "/bin/bash"
args = ["-c", "javac ${SHAWL_FILEPATH} && java -cp $(dirname ${SHAWL_FILEPATH}) ${SHAWL_BASENAME} \"$@\"", "--"]
envs = {}

[shebang]
executable = "/bin/bash"
args = ["-c", "javac ${SHAWL_FILEPATH} && java -cp $(dirname ${SHAWL_FILEPATH}) ${SHAWL_BASENAME} \"$@\"", "--"]
envs = {}

[pipe]
executable = "java"
args = ["-"]
envs = {}

[shell]
executable = "jshell"
args = ["${SHAWL_FILEPATH}"]
envs = {}

[shim]
executable = "/bin/bash"
args = ["-c", "javac ${SHAWL_FILEPATH} && java -cp $(dirname ${SHAWL_FILEPATH}) ${SHAWL_BASENAME} ${SHAWL_FUNCTION} \"$@\"", "--"]
envs = {}
