#!/usr/bin/env node
// ${SHAWL_NAME} script: ${SHAWL_BASENAME}
// Generated by: shawl init

/**
 * Example function that can be called with druid mode
 */
function ${SHAWL_BASENAME}() {
    console.log("Hello from Node.js!");
    console.log("Args:", process.argv.slice(2));
    
    // Access environment variables
    console.log("SHAWL_PATH:", process.env.SHAWL_PATH);
}

// Export for druid mode
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { ${SHAWL_BASENAME} };
}

// Run directly if executed as main module
if (require.main === module) {
    ${SHAWL_BASENAME}();
}
