#!/usr/bin/env perl
# ${SHAWL_NAME} script: ${SHAWL_BASENAME}
# Generated by: shawl init

use strict;
use warnings;

# Example function that can be called with druid mode
sub ${SHAWL_BASENAME} {
    my @args = @_;
    print "Hello from Perl!\n";
    print "Args: @args\n";
    
    # Access environment variables
    print "SHAWL_PATH: $ENV{SHAWL_PATH}\n";
}

# Run directly if executed
unless (caller) {
    ${SHAWL_BASENAME}(@ARGV);
}

1;
