name = "python3"

[default]
executable = "/usr/bin/env"
args = ["python3"]
envs = {}

[druid]
executable = "/usr/bin/env"
args = ["python3", "-c", "import sys; sys.path.insert(0, '${SHAWL_FILEPATH}'.rsplit('/', 1)[0]); from ${SHAWL_BASENAME} import ${SHAWL_FUNCTION}; ${SHAWL_FUNCTION}(*sys.argv[1:])"]
envs = {}

[exec]
executable = "/usr/bin/env"
args = ["python3", "${SHAWL_FILEPATH}"]
envs = {}

[shebang]
executable = "${SHAWL_FILEPATH}"
args = []
envs = {}

[pipe]
executable = "/usr/bin/env"
args = ["python3"]
envs = {}

[shell]
executable = "/usr/bin/env"
args = ["python3", "-i", "${SHAWL_FILEPATH}"]
envs = {}

[shim]
executable = "/usr/bin/env"
args = ["python3", "${SHAWL_FILEPATH}", "${SHAWL_FUNCTION}"]
envs = {}
