#!/usr/bin/env ruby
# ${SHAWL_NAME} script: ${SHAWL_BASENAME}
# Generated by: shawl init

# Example function that can be called with druid mode
def ${SHAWL_BASENAME}(*args)
  puts "Hello from Ruby!"
  puts "Args: #{args.inspect}"
  
  # Access environment variables
  puts "SHAWL_PATH: #{ENV['SHAWL_PATH']}"
end

# Run directly if executed
if __FILE__ == $0
  ${SHAWL_BASENAME}(*ARGV)
end
